use std::fmt::Write;

/// Generate Rust source from Pkl schema source text.
///
/// This is a simplified parser that handles common Pkl class definitions
/// and type aliases. It does not implement a full Pkl parser.
pub fn generate(pkl_source: &str, module_name: &str) -> Result<String, Box<dyn std::error::Error>> {
    let mut output = String::new();

    writeln!(
        output,
        "// Generated by pkl-gen-rust from {module_name}.pkl"
    )?;
    writeln!(output, "// Do not edit manually.")?;
    writeln!(output)?;
    writeln!(output, "use serde::Deserialize;")?;
    writeln!(output)?;

    let classes = parse_classes(pkl_source);
    let type_aliases = parse_type_aliases(pkl_source);

    for alias in &type_aliases {
        write_type_alias(&mut output, alias)?;
    }

    for class in &classes {
        write_class(&mut output, class)?;
    }

    Ok(output)
}

#[derive(Debug)]
struct PklClass {
    name: String,
    properties: Vec<PklProperty>,
}

#[derive(Debug)]
struct PklProperty {
    name: String,
    pkl_type: String,
}

#[derive(Debug)]
struct PklTypeAlias {
    name: String,
    variants: Vec<String>,
}

fn parse_classes(source: &str) -> Vec<PklClass> {
    let mut classes = Vec::new();
    let mut lines = source.lines().peekable();

    while let Some(line) = lines.next() {
        let trimmed = line.trim();
        // Match: class Name { or class Name extends Parent {
        if let Some(rest) = trimmed.strip_prefix("class ") {
            let name = rest
                .split_whitespace()
                .next()
                .unwrap_or("")
                .trim_end_matches('{')
                .trim()
                .to_string();

            if name.is_empty() {
                continue;
            }

            let mut properties = Vec::new();
            // Read until closing brace
            for prop_line in lines.by_ref() {
                let prop_trimmed = prop_line.trim();
                if prop_trimmed == "}" {
                    break;
                }
                if prop_trimmed.is_empty() || prop_trimmed.starts_with("//") {
                    continue;
                }
                // Match: propertyName: Type
                if let Some((prop_name, prop_type)) = parse_property_line(prop_trimmed) {
                    properties.push(PklProperty {
                        name: prop_name,
                        pkl_type: prop_type,
                    });
                }
            }

            classes.push(PklClass { name, properties });
        }
    }

    classes
}

fn parse_property_line(line: &str) -> Option<(String, String)> {
    // Handle: name: Type or name: Type = defaultValue
    let line = line
        .trim_start_matches("hidden ")
        .trim_start_matches("fixed ");
    let parts: Vec<&str> = line.splitn(2, ':').collect();
    if parts.len() != 2 {
        return None;
    }
    let name = parts[0].trim().to_string();
    let type_part = parts[1].split('=').next().unwrap_or("").trim().to_string();
    if name.is_empty() || type_part.is_empty() {
        return None;
    }
    Some((name, type_part))
}

fn parse_type_aliases(source: &str) -> Vec<PklTypeAlias> {
    let mut aliases = Vec::new();

    for line in source.lines() {
        let trimmed = line.trim();
        if let Some(rest) = trimmed.strip_prefix("typealias ") {
            // typealias Name = "A"|"B"|"C"
            let parts: Vec<&str> = rest.splitn(2, '=').collect();
            if parts.len() != 2 {
                continue;
            }
            let name = parts[0].trim().to_string();
            let rhs = parts[1].trim();
            let variants: Vec<String> = rhs
                .split('|')
                .map(|s| s.trim().trim_matches('"').to_string())
                .filter(|s| !s.is_empty())
                .collect();
            if !variants.is_empty() {
                aliases.push(PklTypeAlias { name, variants });
            }
        }
    }

    aliases
}

fn write_type_alias(
    output: &mut String,
    alias: &PklTypeAlias,
) -> Result<(), Box<dyn std::error::Error>> {
    writeln!(
        output,
        "#[derive(Debug, Clone, PartialEq, Eq, Deserialize)]"
    )?;
    writeln!(output, "pub enum {} {{", alias.name)?;
    for variant in &alias.variants {
        let rust_variant = to_pascal_case(variant);
        writeln!(output, "    #[serde(rename = \"{variant}\")]")?;
        writeln!(output, "    {rust_variant},")?;
    }
    writeln!(output, "}}")?;
    writeln!(output)?;
    Ok(())
}

fn write_class(output: &mut String, class: &PklClass) -> Result<(), Box<dyn std::error::Error>> {
    writeln!(output, "#[derive(Debug, Clone, Deserialize)]")?;
    writeln!(output, "pub struct {} {{", class.name)?;
    for prop in &class.properties {
        let rust_name = to_snake_case(&prop.name);
        let rust_type = pkl_type_to_rust(&prop.pkl_type);
        if rust_name != prop.name {
            writeln!(output, "    #[serde(rename = \"{}\")]", prop.name)?;
        }
        writeln!(output, "    pub {rust_name}: {rust_type},")?;
    }
    writeln!(output, "}}")?;
    writeln!(output)?;
    Ok(())
}

fn pkl_type_to_rust(pkl_type: &str) -> String {
    let trimmed = pkl_type.trim();

    // Nullable types: Type?
    if let Some(inner) = trimmed.strip_suffix('?') {
        return format!("Option<{}>", pkl_type_to_rust(inner));
    }

    // Collection types
    if let Some(inner) = extract_generic(trimmed, "List") {
        return format!("Vec<{}>", pkl_type_to_rust(&inner));
    }
    if let Some(inner) = extract_generic(trimmed, "Listing") {
        return format!("Vec<{}>", pkl_type_to_rust(&inner));
    }
    if let Some(inner) = extract_generic(trimmed, "Set") {
        return format!("Vec<{}>", pkl_type_to_rust(&inner));
    }
    if let Some((k, v)) = extract_map_generic(trimmed, "Map") {
        return format!(
            "std::collections::HashMap<{}, {}>",
            pkl_type_to_rust(&k),
            pkl_type_to_rust(&v)
        );
    }
    if let Some((k, v)) = extract_map_generic(trimmed, "Mapping") {
        return format!(
            "std::collections::HashMap<{}, {}>",
            pkl_type_to_rust(&k),
            pkl_type_to_rust(&v)
        );
    }

    // Primitive types
    match trimmed {
        "String" => "String".into(),
        "Int" | "Int8" | "Int16" | "Int32" => "i64".into(),
        "UInt" | "UInt8" | "UInt16" | "UInt32" => "u64".into(),
        "Float" => "f64".into(),
        "Boolean" => "bool".into(),
        "Duration" => "pklrust::Duration".into(),
        "DataSize" => "pklrust::DataSize".into(),
        "Any" => "serde_json::Value".into(),
        "Dynamic" => "serde_json::Value".into(),
        other => other.to_string(), // User-defined type
    }
}

fn extract_generic(s: &str, prefix: &str) -> Option<String> {
    let s = s.trim();
    if let Some(rest) = s.strip_prefix(prefix) {
        if let Some(inner) = rest.strip_prefix('<') {
            if let Some(inner) = inner.strip_suffix('>') {
                return Some(inner.trim().to_string());
            }
        }
        // List without type parameter
        if rest.is_empty() {
            return Some("serde_json::Value".to_string());
        }
    }
    None
}

fn extract_map_generic(s: &str, prefix: &str) -> Option<(String, String)> {
    let s = s.trim();
    if let Some(rest) = s.strip_prefix(prefix) {
        if let Some(inner) = rest.strip_prefix('<') {
            if let Some(inner) = inner.strip_suffix('>') {
                // Find the comma that separates key and value types
                // Handle nested generics by counting angle brackets
                let mut depth = 0;
                for (i, ch) in inner.char_indices() {
                    match ch {
                        '<' => depth += 1,
                        '>' => depth -= 1,
                        ',' if depth == 0 => {
                            let key = inner[..i].trim().to_string();
                            let val = inner[i + 1..].trim().to_string();
                            return Some((key, val));
                        }
                        _ => {}
                    }
                }
            }
        }
    }
    None
}

fn to_snake_case(s: &str) -> String {
    let mut result = String::new();
    for (i, ch) in s.chars().enumerate() {
        if ch.is_uppercase() && i > 0 {
            result.push('_');
        }
        result.push(ch.to_lowercase().next().unwrap());
    }
    result
}

fn to_pascal_case(s: &str) -> String {
    let mut result = String::new();
    let mut capitalize_next = true;
    for ch in s.chars() {
        if ch == '_' || ch == '-' || ch == ' ' {
            capitalize_next = true;
        } else if capitalize_next {
            result.push(ch.to_uppercase().next().unwrap());
            capitalize_next = false;
        } else {
            result.push(ch);
        }
    }
    result
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_pkl_type_to_rust() {
        assert_eq!(pkl_type_to_rust("String"), "String");
        assert_eq!(pkl_type_to_rust("Int"), "i64");
        assert_eq!(pkl_type_to_rust("Float"), "f64");
        assert_eq!(pkl_type_to_rust("Boolean"), "bool");
        assert_eq!(pkl_type_to_rust("String?"), "Option<String>");
        assert_eq!(pkl_type_to_rust("List<String>"), "Vec<String>");
        assert_eq!(
            pkl_type_to_rust("Map<String, Int>"),
            "std::collections::HashMap<String, i64>"
        );
    }

    #[test]
    fn test_generate_class() {
        let source = r#"
class Server {
  host: String
  port: Int
  tags: List<String>
}
"#;
        let result = generate(source, "test").unwrap();
        assert!(result.contains("pub struct Server"));
        assert!(result.contains("pub host: String"));
        assert!(result.contains("pub port: i64"));
        assert!(result.contains("pub tags: Vec<String>"));
    }

    #[test]
    fn test_generate_type_alias() {
        let source = r#"
typealias Environment = "development"|"staging"|"production"
"#;
        let result = generate(source, "test").unwrap();
        assert!(result.contains("pub enum Environment"));
        assert!(result.contains("Development"));
        assert!(result.contains("Staging"));
        assert!(result.contains("Production"));
    }

    #[test]
    fn test_to_snake_case() {
        assert_eq!(to_snake_case("serverName"), "server_name");
        assert_eq!(to_snake_case("hostURL"), "host_u_r_l");
        assert_eq!(to_snake_case("port"), "port");
    }
}
